### ISSUE TITLE
RS www-authenticate response

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#118]
§10.4 Requesting a Resource With Insufficient Access: Editor's note: 

This borrows heavily from UMA 2's "distributed authorization" model and, like UMA, might be better suited to an extension than the core protocol.

**Comment by davidgtonge** [comment]
I'm in favour of this being in the core protocol. I don't think it adds that much complexity and it opens up a whole world of different deployment options.

**Comment by yaronf** [comment]
First, the sentence at the top of this section is broken: `indicating that GNAP`.

Second, I think this is a complicated decision:
* The RC is more likely to assume it will receive a useful response if this is in the core document rather than an extension.
* There may be privacy issues with the RS reporting the AS URI for a particular resource. Which would argue against including it in the core protocol.

**Comment by davidgtonge** [comment]
It is definitely something that would be hard to make "mandatory to implement". I would like to see it included but not mandated for all deployments.
