### ISSUE TITLE
Redirect to an Arbitrary Shortened URL

### ISSUE THREAD

**Issue by davidgtonge** [ietf-wg-gnap/gnap-core-protocol#121]
I don't understand why this mode is needed?

Its also problematic having a boolean or a number as valid parameters for `interact.redirect`

**Comment by jricher** [comment]
Polymorphism in the protocol is discussed as part of a larger design question in #6 

The short redirect was suggested in early WG (or even pre-WG) design discussions to allow the client to request a redirect URI with limitations on its final length, to facilitate the client communicating it to the user in limited ways. There are still a lot of questions about this including whether it stays switched like this and what the error/failure modes would be, #53

**Comment by davidgtonge** [comment]
Thanks for the explanation, it would be good to link this to a documented use case - I couldn't see one in the wiki.

I'll leave a comment in #6 as I think that a high level polymorphism is a good fit for the protocol, but it should be used sparingly. I see no reason for it to be used here.

**Comment by fimbault** [comment]
If we are to shorten the URL (which is a valid use case, especially if a user needs to copy paste it manually from a constrained device to some other browsing device), then it seems logical to really limit the value instead of defining an "integer indicating the maximum character length of the returned URL" (255 in the example). For the manual use case, it seems too big to be practical, and there are other conditions besides length that matter (which set of characters, entropy threshold, etc.). See https://github.com/ai/nanoid for instance, and its demo https://zelark.github.io/nano-id-cc/

This means we could avoid parameters, and choose a predefined setting that does the job. 

![image](https://user-images.githubusercontent.com/45664395/99245322-ab5ddb80-2803-11eb-961f-e9b8863140f5.png)

**Comment by jricher** [comment]
For things you expect a human to type, you should be using the `user_code` method with a static URL instead since it allows you to separate the human-memorable part from the URL part. 

The drive for this mode was for clients that had limited capabilities in display but could still communicate something as long and complex as a URI.

For what it's worth, I personally don't think we need this mode and would be fine if we dropped this function.

**Comment by fimbault** [comment]
Ok makes sense.  
Also think it could be dropped because it's a bit confusing.

**Comment by aaronpk** [comment]
Unless there’s a specific use case this enables that we can document in the spec I would also be in favor of dropping this mode.
