### ISSUE TITLE
Syntax of Flags

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#13]
**Yaron**: why are flags represented as resources? The answer, "this is how OAuth 2 does it" is not great.

**Justin**: The idea is that these are items that alter what the access token that’s being requested in the “resources” section. It is a sensible way to hang things together since everything in the array ties to a specific access token. This was a proposed design compromise, and if these flags can fit elsewhere then we can do that.

**Yaron**: this still doesn't explain why we don't have a `flags` object (or array), parallel to the `resources` array.

**Comment by jricher** [comment]
I think this begs the question of whether we'd like a higher-level construct per access token. Right now we only have the `resources` array but perhaps the request could incorporate a more descriptive `access_token` request object that includes the `resources` array and possibly other items, like flags.

**Comment by yaronf** [comment]
Makes sense. But I think this depends on whether and how we want to support the "multiple access tokens" feature. I suggest to resolve that discussion first.

**Comment by jricher** [comment]
Right, this is definitely related to the syntax discussed in #10 . One potential way to handle it would be for a single `access_token` request to be an object with a `resources` array, but a multiple access token request as an array of single access token requests. The problem is labeling the request in such a way as to ensure the client knows what to do with the resulting tokens, but that can be discussed in #10.
