### ISSUE TITLE
GNAP for Custodial SSI Wallets

### ISSUE THREAD

**Issue by agropper** [ietf-wg-gnap/gnap-core-protocol#175]
The SSI standards often presume a secure ‘wallet’ app on a personal device, human interaction for each authorization, and strive to avoid dependence on HTTP. Many use-cases, however, would prefer a wallet in the cloud with the option for policy-based authorizations that does not wait for a direct action from the resource owner. This cloud or custodial wallet is effectively an agent of the resource owner and bears the costs and risks of such a fiduciary role. 

The custodial wallet could be a GNAP authorization server. The security risk would be minimized if the authorization policies and resource owner credentials it holds are encrypted at rest. Secure multi-party computation with a mobile wallet could be an eventual solution. A nearer-term solution would have the AS access the secret policies and credentials in the mobile wallet only when an authorization request is being serviced.

- How would an AS connect to a mobile app in order to get confidential polices and credentials?
- Or, do we expect the AS to forward the request to the mobile app and wait for the authorization to be returned somehow?
- If there’s an encrypted data vault online, does the AS or the mobile app use that as a resource server for credentials and how does the client get the decryption keys?

**Comment by fimbault** [comment]
Cloud wallets have indeed been developed in the cryptospace, see for instance what zengo is doing with threshold cryptography (note that this still assumes a key on a mobile device). Interestingly they position themselves as non custodial and keyless (which is a marketing overstatement, because keys still exist of course, but the tech is interesting). 

There's also a variety of KMS solutions (hardware or software), and the new kid on the block is DIF KERI. An example of API above a vault is provided by [hashicorp](https://www.vaultproject.io/api-docs/secret/key-management#read-key), alas only in their entreprise version.
