### ISSUE TITLE
sub_ids and different contexts

### ISSUE THREAD

**Issue by adeinega** [ietf-wg-gnap/gnap-core-protocol#178]
It may make sense to use 

1. subject_types (or subject_type_identifiers) instead of sub_ids in section 2.2. Requesting Subject Information

> sub_ids (array of strings) An array of subject identifier subject types requested for the RO...

2. subject_types (or subject_type_identifiers) instead of sub_ids in section 9. Discovery

> sub_ids (array of strings) OPTIONAL. A list of the AS's supported identifiers.

The reason for it is that the same sub_ids has a different meaning in section 3.4. Returning User Information, where it's

> sub_ids (array of objects) An array of subject identifiers for the RO

and so on.

Furthermore, `A list of the AS's supported identifiers.` in section 9. Discovery could be changed to `A list of the AS's supported identifier types.` for clarity.

See also https://github.com/ietf-wg-gnap/gnap-core-protocol/pull/177

**Comment by jricher** [comment]
I like this idea, as these really are two different entities with different purposes.

**Comment by fimbault** [comment]
Makes sense on the general idea. 
Made some comments on the PR regarding the label.

**Comment by fimbault** [comment]
This also questions what could be the types of sub_ids
-> we currently refer to https://www.ietf.org/archive/id/draft-ietf-secevent-subject-identifiers-06.txt
-> but that could also be DIDs (cf #171)
-> or a unique identifier local to the AS: as_uid (suggestion to be used as an example instead of email, cf #16), this would be opaque to other systems but enough for a client to distinguish users (just like using a database identifier)
