### ISSUE TITLE
References and Their Lifecycle

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#19]
**Yaron**: 2.4.1 (but probably applicable to any references): what is the lifetime of the reference? As an RC, how long can I assume the user reference is still valid?

**Justin**: That’s up to the AS ultimately. Previous editions of the XYZ Protocol had lifetimes and other things tied to the reference handles (defined in section 3.5), but it didn’t seem like anyone actually cared about those parts in practice. A reference is either going to work, or it won’t, and it could fail for reasons that have nothing to do with a timeout that the RC can’t control or have input into.

**Yaron**: I see your point but it makes the whole notion of references very weak. If references can disappear at any time and for any reason, the RC needs to have retry logic that replaces all references by the full object. I can easily see that people will punt references and simply send the object every time.

**Comment by jricher** [comment]
This is a great point. If the client has a full object, then it is certainly simpler to send the whole object. I think we'll see a lot of "dumb" clients doing exactly this behavior. They won't deal with or remember dynamic identifiers, they'll just send whatever they were given every time. 

But the same could be true for the references themselves. For example, in many cases, the references are going to be defined AS-side and the client will only have those to use, not the "objects" they would represent to the AS. This is the case for a statically registered `instance_id` for the client software as well as the resource references. The user reference mentioned here might not be the result of the RC sending a `user` object in the first place, but like UMA, it could be the result of the AS interacting with the RO and the RO indicating that this instance of software should "remember them" over time. In this case, the client never had a full object to send since the "object" represented by the reference is only known to the AS itself.

I think there are a lot of use cases for references throughout the protocol that can be a bit subtle so it's important to have them laid out. I don't think current document does as good a job at capturing these different dimensions as it could.

**Comment by jricher** [comment]
All references are now clearly defined as AS-controlled values, and so the client instance will use it assuming that it works, not expecting to dynamically manage the instance identifier itself.
