### ISSUE TITLE
Proving Possession of a Key for the AS and RS

### ISSUE THREAD

**Issue by adeinega** [ietf-wg-gnap/gnap-core-protocol#196]
The _Proving Possession of a Key with a Request_ section explicitly states that

> Any keys presented by the client instance to the AS or RS MUST be validated as part of the request in which they are presented

1. Unfortunately, I don't see how a client can make use of the jws param (Attached JWS payload) to make calls to "regular" RSs. Normally, they won't be ready to accept the "application/jose" content type and the corresponding payload for the endpoint that accepts say "application/json" and "application/xml".

2. I also believe that this specification shouldn't require the payload (HTTP Body) to be included in the calculation of the JWS signature for RSs in case of Detached JWS payload. The reason is that the client (or any logic that validates access tokens) doesn't always have access to the payload and the bright example for this would be NGinx and [its auth_request module](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html). Note, this approach isn't limited in any way to NGinx and is extremely popular among various cloud providers. There are also other minor reasons say just huge payloads (like a movie upload) or even a real-time stream (WebRTC) and so on and so forth.

Both these items are totally fine and definitely should be required for any calls from a client to an AS though.

**Comment by adeinega** [comment]
https://tools.ietf.org/html/draft-ietf-oauth-dpop-02 says this about the payload and HTTP headers

> DPoP does not directly ensure message integrity but relies on the TLS layer for that purpose.

and

> DPoP does not ensure the integrity of the payload or headers of requests.  The DPoP proof only contains claims for the HTTP URI and method, but not, for example, the message body or general request headers.
> 
> This is an intentional design decision intended to keep DPoP simple to use, but as described, makes DPoP potentially susceptible to replay attacks where an attacker is able to modify message contents and headers.  In many setups, the message integrity and confidentiality provided by TLS is sufficient to provide a good level of protection.
> 
> Implementers that have stronger requirements on the integrity of messages are encouraged to either use TLS-based mechanisms or signed requests.

**Comment by jricher** [comment]
Attached JWS is highly problematic and limited for exactly the reason you describe: it requires the API the client is calling to accept a JOSE encoded payload instead of its native payload (see #109). Plus, this only works for requests with a message body (POST/PUT) so you need to fall back to the detached method for other verbs, and it's really only mostly applicable for JSON payloads though technically you can serialize anything in a JWS so that's  just more it feeling "weird" than being wrong. I'm personally not a fan of the method for all these reasons, but several members of the WG have stated that it fits their use cases better than other methods.

Inclusion of the body (when present) in the detached JWS request allows it to be validated along with the signature in the reset of the request. A library outsourcing GNAP with something like an auth_request module would need to include the signature calculation in that module, like here: https://github.com/bspk/oauth.xyz-java/blob/master/rc/src/main/java/io/bspk/oauth/xyz/http/SigningRestTemplateService.java

An AS is just as likely to be behind a security layer proxy, either externalized as you describe or internal to the app like in Java's servlet filter system. In any event, to handle body integrity you're going to have to handle this as part of the filtering system, like here: https://github.com/bspk/oauth.xyz-java/blob/master/lib/src/main/java/io/bspk/oauth/xyz/http/DigestWrappingFilter.java ... and to me, it's really not any dissimilar to TLS reverse proxies.

As for DPoP, note that we're only using the signature method of DPoP here, not the whole protocol extension in its context. The restrictions and guidance you've quoted come from the fact that DPoP is targeted specifically at SPA's running OAuth 2, and so the advice does not apply here.

**Comment by adeinega** [comment]
The changes to get the whole request body in such externalized components in the Kubernetes (and its friends) world are very slim as that somehow defeats the benefits of its use. Note, this component doesn't act as a proxy. It receives all or only certain headers of an HTTP request, does its own business, and then finally tells whether access is granted. If granted, the whole HTTP request gets forwarded to the right service to be processed further. If not, a caller gets 401 or an HTTP redirect, etc.

https://doc.traefik.io/traefik/middlewares/forwardauth/ is another example of a component that does pretty much the same as NGinx's auth_request module. There is a bunch of other similar components.

I do like that GNAP requires "body" integrity for all interactions between a client and an AS. It feels for me it should be optional for interactions between a client and an RS.

**Comment by jricher** [comment]
This is where things like the HTTP Message Signatures could help, since the body hash is separate from the signing. The client can calculate the body Digest header and pass that along to the signing component.

It could also be that the security components get redesigned to accommodate the security protocols. We already saw that shift when API libraries started handling access tokens instead of just HTTP Basic username/password combos, which is all they used to do. Or when browsers adopted the fetch() API as opposed to the deeply limited capabilities that were there before. Now, I'm not saying that GNAP should count on the world bending to its will, or that we should ignore deployment patterns; but we also shouldn't limit the protocol based on a design choice in software that makes sense today and might not in the future. These libraries only look at a couple headers because that's all they need to do right now, much like in the past they would have just taken in a username and password.

**Comment by adeinega** [comment]
These external components don't really have a choice to read only certain headers or the whole request. They get only what they get from ingress controllers in a cluster. It's very possible that in the future, these controllers (like NGinx or Traefic) will have to provide the SHA-256 hash of the request's payload in order to accommodate the security protocols as you said. It's hard to predict when and if it will happen at all. As of today, this is a very common and extremely popular deployment model.

**Comment by jricher** [comment]
The approach proposed in #201 should address these concerns by and large, and this issue will close with #201
