### ISSUE TITLE
Definition of a Subject in section 1.3

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#198]
In section 1.3, subject is defined as:

    Subject 
    person, organization or device.

Given the current definition of a Right (ability given to a subject to perform a given operation on a resource under the control of a RS), it does not make sense to consider that a subject may also be an organization or a device. 

Delete "organization or a device".

**Comment by fimbault** [comment]
We're mostly interested in having definitions which are consistent throughout the document. In the context of a right associated to an end-user, it is usually applicable to a person. But even then the right could derive from an automatic RBAC system as well. There are other places where subject is applicable to an organization or an IT system, especially for the resource owner. 
Notice the OR statement, depending on the context it may vary.

**Comment by Denisthemalice** [comment]
A resource owner is still a person: it is neither an organization nor a device: it still does not make sense to consider that a subject may also be an organization or a device.

**Comment by fimbault** [comment]
Not always, the resource owner can very well be your company for instance, and the consent might not require a real person (that's the all point of LDAP for instance).

**Comment by Denisthemalice** [comment]
Do you mean that a subject is either an end-user or a resource owner which may then be either  a person or an organization ?
Would you have some arguments for a "subject" being a "device" ?

**Comment by fimbault** [comment]
An end user is only a natural person. A RO could be a natural person, an organisation or a device. In the last 2 cases, you have a rule engine instead of a person.
An example of a device as a resource owner could be a system (ex a robot, a car, etc.) that controls specific resources. Not very common today tbh, but IoT scenarii make that likely in the future (at least I don't see a reason why it shouldn't be included in a generic definition).

**Comment by Denisthemalice** [comment]
This topic is closely related to the issue #197.

 An AS manages end-users and maintains relationships with some ROs, but does not manage organizations, nor devices.

"Requesting Subject information" does not really make sense.

**Comment by fimbault** [comment]
We never said the AS managed organisations or devices, and we didn't say either that it managed users. It manages access tokens.
It's not because the definition might in some cases allow additional cases that it doesn't make sense. We just need to be very specific as to what kind of subject is concerned when it doesn't apply to all.

**Comment by Denisthemalice** [comment]
Humm ! An AS needs to manage end-users because an end-user needs first to authenticate to the AS before the client it is using may obtain an access token. The authentication mechanism being used is left out of the scope of the document, but an authentication exchange must exist. 

Once an end-user has been authenticated, it is possible for the AS to know which are his attributes and upon a request from the client they can be enumerated by the AS.  

"Requesting end-user information" makes sense. while "Requesting Subject information" still does not make sense.

**Comment by fimbault** [comment]
I've reviewed in detail, and I quite definitely think the current definition is fine and fits well with all sequences in 1.4.x. More info also for IETF110.

**Comment by fimbault** [comment]
Closing as discussed last week on the mailing list
