### ISSUE TITLE
The case of attributes should be addressed

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#233]
A privilege is a right or attribute associated with a subject. An access Token contains a set of rights and/or attributes.

The current draft addresses the case of rights, but not the case of attributes.

A key question is the following : since most attributes are personal information, should an end-user be allowed to choose 
which attribute types (and optionally attribute values) should be placed into an access token ?

**Comment by aaronpk** [comment]
Since access tokens are opaque, there is no "into an access token". If an AS decides to use a structured token format, that is outside the scope of GNAP core, and would be best discussed in an extension. This is similar to the relationship between RFC6750 and the [JWT profile for access tokens](https://tools.ietf.org/html/draft-ietf-oauth-access-token-jwt-12).

**Comment by jricher** [comment]
Agree with @aaronpk . An access token can easily be a completely random value used to look up information in the back end, and therefore have no internal data.

**Comment by fimbault** [comment]
I think we should keep the opaque/non opaque discussion aside, since a decision was reached in #145.
Irrespective of that, the current request indeed focuses on rights (called action), it would be helpful to also support basic attributes. "dolphin-metadata" is kind of an attribute, but doesn't relate to a location.

**Comment by jricher** [comment]
covered under discussion in #244
