### ISSUE TITLE
no user involved - client definition

### ISSUE THREAD

**Issue by fimbault** [ietf-wg-gnap/gnap-core-protocol#329]
From #322, account for the many situations in which there is no user -- no person involved in the transaction.

Proposal to update the definition (added part in bold) : 
- Client : application operated by **or on-behalf of** an end-user that consumes resources from one or several RSs,
possibly requiring access privileges from one or several ASs.

**Comment by Denisthemalice** [comment]
@fimbault ; You wrote:

> it's not because you don't have a user that you have no consent. Many policies can be automated.

A user consent may be given (or refused) once a user notice has been able to be accessible to the end-user so that he can know what kind of usage or processing will be made by the RS with his attributes. Even, if the client can cache earlier decisions, the end-user must be able to make his decision based or not on a cached response. Your argumentation seems to me a bit far-fetched.
  
@jricher . You wrote:

> It was always intended that there might not always be a person operating the client instance in real-time, there are several sections in the document that account for this set of use cases. This issue is just aligning the definition with reality, not re-litigating the terminology discussion.

I found a single case on page 118 in section 12.11 (Client Instance Pre-registration) where the end-user is different from the RO.

I would have expected that draft-07 (including this section) would explain the relationships between client instances and end-users and how/when these relationships are established by an AS. Unfortunately, as I already mentioned, draft-07 still does not indicate which relationships exist between client instances and end-users, nor how/when these relationships are established by an AS.

Section 12.11 states:

> It also is sensible to pre-register client instances when the software is acting on its own behalf, without the need for a runtime approval by a resource owner or any interaction with an end-user.

This sentence does not comply with the new definition you are proposing. 

You are proposing :

> Client: application that consumes resources from one or several RSs and receives subject information from an AS, possibly requiring access privileges from one or several ASs. The client is operated by the end-user, or it behaves autonomously on behalf of a resource owner.

The first sentence is fine with me. The first part of the second sentence is also fine with me: "The client is operated by the end-user". 

As far as I understand, the last part of the second sentence only applies in the case where the end-user is also the RO. 
So it does not apply in general.

You know that my main interest is not about the use case where the end-user is also the RO. However for that specific case, you know more that I do, and maybe that specific case should be addressed and explained in a separate sub-section.
