### ISSUE TITLE
Use of the terms URI and URL

### ISSUE THREAD

**Issue by pq2** [ietf-wg-gnap/gnap-core-protocol#341]
In various places in the protocol, the terms _URI_ and _URL_ seem to me to be used more or less synonymously. For example, in [Section 3.1](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-3.1) there is a property `uri` in the `continue` field, while in [Section 3.3.3](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-3.3.3) there is a member `url` in the `user_code` field. Another example is the description of the `redirect` interaction start mode. While in Sections [2.5.1.1](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-2.5.1.1) and [3.3.1](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-3.3.1) the term _URL_ is used consistently, in [Section 4.1.1](https://datatracker.ietf.org/doc/html/draft-ietf-gnap-core-protocol#section-4.1.1) mostly _URI_ is used, but in one sentence _URL_ is used again.

Wouldn't it make sense to make this consistent and always speak of a _URL_, since I assume that the use of Uniform Resource Names (_URNs_) is not intended? Or is there a reason why _URI_ is used in some places and _URL_ in others?

**Comment by fimbault** [comment]
Ok, having looked at this issue a bit more
- There are places where URI is intentional, like 4.1.3. Interaction through an Application URI. 
- There are places where URI is provided because it's the most generic possibility, e.g. "This URI MUST be protected by HTTPS, be hosted on a server local to the RO's browser ("localhost"), or use an application-specific URI scheme." (2.5.2) or "he client instance could launch the URI through the system browser, provide a clickable link, redirect the user through HTTP response codes, or display the URI in a form the end user can use to launch such as a multidimensional barcode." (4.1.1)
- in RAR, locations are defined as URIs : "These strings are typically URIs identifying the location of the RS."
- But there are also places where it's unclear : "The URI MUST be accessible from an HTTP GET request and MUST be protected by HTTPS or equivalent means." (effectively that's an URL)
- Most of the examples are URL, even when the field is labeled URI
- Section 1.5.2 (user code interaction) and 3.3.3 use an URL, probably because it's supposed to be statically configured, but after all, nothing really forbids an URI here too in principle (by definition, the identifier is stable, which is what is really required). See for instance : "While this URL is generally hosted at the AS, the client instance can make no assumptions about its contents, composition, or relationship to the AS grant URL."
- We have many cases where we mix URI and URL in the same place (ex 4.2.1, title and text don't match)

In general, URI matches better with the intent that the identifier may be reachable through various/generic means. 
Also RFC3986 is a mess and now quite old, but it does say that re specifications and related documentation should use the general term "URI" rather than the more restrictive terms "URL" and "URN" [RFC3305] (1.1.3). 
All that goes into the direction of using URI indeed.
But in practice, most real cases probably will be using URLs in practice. Then https://url.spec.whatwg.org/ explains quite well that "URI and IRI are just confusing". URL wins the popularity contest https://trends.google.com/trends/explore?q=url,uri

The only places where URLs are needed seem to be : 
- in the subject identifiers, for DIDs (in the related example). 
- in 4.2.3.1 and 4.2.3.2, for base64 encoded URLs with no padding (+ by the way, we should explain what we mean by no padding and URL safe)
- in 7.1, cert#S256 (string) is a URL 
- in 7.1.1, "a client publishing a public key at a URL" (since we're refering to a practical use case)
- in 7.3.1, http message signing refers to URLs and https://url.spec.whatwg.org/ in particular
- in 7.3.3, jws
- many places in the security considerations provide wisdom for real implementations, which do refer to URLs, and I would tend to think that makes more sense

Therefore here is what I suggest : 
- change all URL to URI, except in the cases mentioned just above
- if it helps, we could include an additional description in the elements, clarifying in one single that the various possibilities for URIs in our protocol, instead of repeating in multiple places. Knowing that most of our examples and security considerations are based on URLs. 

Let me know what you think, it's in so many places (also in section links) that I prefer to check before...
