### ISSUE TITLE
Both attributes (ABAC) and capabilities (CBAC) SHOULD be supported

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#371]
At the moment, a client is able to request with a fine degree a precision a specific set of rights that should be included into an access token. However, a client is unable to request a specific set of attributes that should be included into an access token. 

As a consequence, the support of rights versus the support of attributes is unbalanced.

Implicitly, the core draft mandates a bilateral pre-relationship between every pair of AS / RS. This is not advertised in the draft.

Such bilateral pre-relationship limits the scalability of the architecture. When attributes only are supported, no bilateral pre-relationship between an AS and a RS is necessary.

The core document implicitly only allows an AS to add attributes into an access token at its own discretion, without any specific request for them to be included from the client (and hence the end-user).

This means that the core document does not allow an AS to add specific attributes into an access token upon the request from the client (and hence from the end-user).

This has severe consequences in term of the end-user privacy which are not mentioned in the draft.

First of all, since rights are always included, this means that the AS MUST be aware of the identity of the RS. In addition, the AS cannot be kept ignorant of which actions will be performed by a client and on which resources. **_This allows the AS to act as "Big Brother"._** However, this can be prevented in the case where attributes only are supported.

Secondly, in order to support "good practices" (**_User Notice, User Choice, User Consent and Transparency_**) or legislation like the EU GDPR, the end-user should be informed about the set of attributes that are requested by a RS and should also be able to know the treatment(s) that will be done with such attributes. At the moment, a dialogue between the client and the RS is missing. A specific RS end-point should be defined and dedicated for such dialogue.

If the end-user agrees to provide that set of attributes to the RS, he should be able to indicate to the AS which attributes types (and optionally values) should be included into the access token. At the moment, the client is unable to specify to the AS a set of attributes to be included into the access token. In addition, an end-user is even unable to know which set of attributes are known by the AS.

If this situation is going to last, the privacy consideration section should clearly indicate these limitations.

**Comment by agropper** [comment]
Although I disagree with this proposal, it might be useful for GNAP to be
more explicit as to why attributes are not in scope.

From my privacy-inspired perspective, it's essential that GNAP represents a
separation of concerns between possession (RS) and control (AS). This means
that the RS should be kept in the dark as much as possible and
attribute-based client requests should be received by the AS to the largest
extent possible.

Another way to say this is that GNAP should not encourage RO policies to be
shared with the RS. This does not mean that RS doesn't have policies of its
own and, to the extent the RS has a relationship with the RO, the RO might
choose to share RO policies with the RS, but that would be outside of GNAP
from my perspective.

Adrian

**Comment by jricher** [comment]
@agropper the attributes model is already fully supported by the current documents, as has been demonstrated many times. The assertions in this issue are false. Since attributes are such a wide net that mean a huge variety of things, it's going to be very specific to the API being protected and so the spec is silent about them while allowing them. The details of the sharing between AS and RS are separate from the core document, also, and since this doesn't affect the relationship to the client it doesn't go in here. The RS draft might talk about this as part of the token model discussion, as has been said previously.

It's important not to conflate what the client instance asks for (the `access` array, same as in RAR) with the rights, attributes, and policies shared via the token (either internally or by reference). It is a core design decision that these are separate from each other as it allows for greater privacy and security in a wide variety of situations. GNAP does not encourage or discourage RO policies to be shared with the RS -- it's up to the RS to define how it needs to understand the request.

**Comment by Denisthemalice** [comment]
@jricher . You wrote:

> The assertions in this issue are false

Please read them again: they are true. 
If you believe that some of them are incorrect, please point to the sentence(s) you believe is(are) incorrect.

The title of this issue is : Both attributes (ABAC) and capabilities (CBAC) SHOULD be supported.

This means that the access control should be able to be based:
1) on capabilities only,
2) on both capabities and attributes, and
3) on attributes only.

The first case is clearly supported.

The second case is more or less supported, since the end-user is completely blind upon the attributes that will be incorporated into the access token.

The third case is not currently supported.

**Comment by jricher** [comment]
@Denisthemalice I have read and fully understood this post all of the times you have made it previously. You are incorrect and it has been demonstrated many times, though you have yet to accept any explanations as to why.

It is up to the agreement between the AS and RS what the token represents. The token can represent attributes about the user just as easily as anything else, based on the needs of the RS and abilities of the AS. GNAP is an independent carrier of all of these things.

**Comment by Denisthemalice** [comment]
@jricher ; You wrote:

> It is up to the agreement between the AS and RS what the token represents.

This is the current case with OAuth. OAuth is a framework.

Since GNAP is supposed to become an interoperable protocol, a RS should be able to separate the capabilities from the rights that may be present in an access token and understand the semantics of each item in each category. This is indeed currently possible for the capabilities, but not for the attributes.

This is another argument why I wrote:

> As a consequence, the support of rights versus the support of attributes is unbalanced.

At this time, with a fine level of granularity, the client can specify to the AS the capabilities that it wants to be included into the access token, but not the attributes. Once again:

> As a consequence, the support of rights versus the support of attributes is unbalanced.

OAuth was using a scope parameter that was not understandable by the client, nor the end-user. 

I believe that GNAP should go further and get rid of the scope which mandates a prior agreement between each RS and each AS
and does not allow the end-user to control which attributes will be placed into the access token. 

This is fairly important from an **_end-user privacy_** perspective.

**Comment by agropper** [comment]
@Denis, From my privacy perspective, it seems like I’m looking for the
opposite from you. My intent is separation of concerns where the RS, by
definition, is as blind as possible to client attributes or intent relative
to the AS as controller of a resource.

This does not mean that the RS can’t make demands of its own as part of the
RS-AS relationship but RS-Client demands would be treated as an exception /
censorship.

The end user certainly has a right to privacy but that has almost nothing
to do with it because, by definition, the resource is controlled by the AS.
The end user has rights to privacy for the resources that it controls.
Joint control of resources is an interesting topic that has been discussed
in other threads.

- Adrian

**Comment by Denisthemalice** [comment]
**_@Adrian._**

You wrote: 

> " by definition, the resource is controlled by the AS."

This is true in the case of a CBAC model, but not for an ABAC model.

In an ABAC model, the AS issues end-user attributes that will be checked by the RS, usually using ACLs, i.e. Access Control Lists.
The AS has no clue about the operation(s) that the client will attempt to perform when using these attributes.

When a RS supports an ABAC model,  if the client indicates to the RS the operation that it is willing to perform, the client should be able to query the RS to know which attribute types might allow it to get an access. 

The RS also indicates from which ASs (note the plural) these attribute types may be obtained. At this point of time, the client has not yet contacted any AS, since it needs to make a decision whether it accepts to contact one of these ASs to get these attribute types.

This is at this moment that the privacy of the end-user is taken into consideration: **_User Notice, User Choice, User Consent_**.
When the access token is returned by the AS to the client, then the fourth privacy principle applies: **_Transparency_**, to make sure that the access token contains no more than what has indeed been requested.

You also wrote:

> The end user has rights to privacy for the resources that it controls.

The end user does not necessarily control any resource, but want to access a resource controlled by a RS.

**Comment by jricher** [comment]
> " by definition, the resource is controlled by the AS."

This is true whether an ABAC, CBAC, RBAC, or any other model is used because the AS is the component that controls what is inside the token, which is interpreted by the RS. This is why GNAP already supports all of these. It does not do it in the way that you describe above, but as has been explained many times, it is supported.

**Comment by Denisthemalice** [comment]
**@jricher**. You claim that both models are supported since access tokens can contain capabilities and/or attributes.

However, this is not sufficient. The key point is whether the client has the ability to ask for capabilities and/or attributes with an equal level of granularity.

An access control scheme can be based:
1.	on capabilities only,
2.	on attributes only, and
3.	on both capabilities and attributes.

In the first case, the client has the ability to ask for capabilities with a fine level of granularity. This is typically the case of a CBAC model. This case is currently supported.

The second case is not currently supported. This is typically the case of an ABAC model.

In the third case, the client has the ability to ask for capabilities with a fine level of granularity while end-user attributes can be added by the AS at its own discretion. This case is currently supported.

**Comment by fimbault** [comment]
Closing as already answered several times
