### ISSUE TITLE
Awkward wording around Client Instance Identifiers

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#396]
The text says:

> Dynamically generated client instance identifiers are string values that MUST be
protected by the client instance as secrets. Instance identifier values MUST be unguessable
and MUST NOT contain any sensitive information.

This is weird, because we're saying both that they should be treated as secrets *and* that they are not sensitive. I would suggest instead:

> Dynamically generated client instance identifiers are string values that MUST be
protected by the client instance as secrets. Instance identifier values MUST be unguessable
and MUST NOT contain any information that would compromise the AS if revealed.

**Comment by jricher** [comment]
We're not saying that they're not sensitive, we're saying that they can't **contain** sensitive information. This is like saying your password is sensitive and it also shouldn't contain your medical record number at your hospital, because that's also a sensitive piece of information. Still I think the wording is an improvement, thanks!

**Comment by fimbault** [comment]
I agree the proposed wording is better, thanks !
