### ISSUE TITLE
Assertion format names

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#41]
§2.2 Requesting User Information: Editor's note: 

The `assertions` values are lifted from [[RFC8693](https://www.rfc-editor.org/info/rfc8693)]'s "token type identifiers" list, but is there a better source?

§2.4: Identifying the User: Editor's note:

The `assertions` keys are lifted from [RFC8693]'s "token type identifiers" list, but is there a better source? Additionally: should this be an array of objects with internal typing like the sub_ids? Do we expect more than one assertion per user anyway?

§3.4 Returning User Information: Editor's note:

Should `assertion` be an array of objects with internal typing like the sub_ids? Do we expect more than one assertion per user anyway?

**Comment by fimbault** [comment]
A related topic is [verifiable claims](https://w3c.github.io/webpayments-ig/VCTF/charter/faq.html)

A specific type of assertion is used in #171 to prove ownership of a sub

**Comment by adeinega** [comment]
I think that `assertion` should be an `array of objects` in "Returning User Information". If not, at least, it could be renamed to "assertion" because the current draft uses "assertions" and defines it as `object`. This is a minor editorial thing though. The more major thing is that what are the strong reasons even to mention SAML assertions in the spec? In recent times, XML is often referred to as a potentially insecure format which isn't great due to a long list of vulnerabilities in XML libraries.

**Comment by fimbault** [comment]
We'll discuss that and more at IETF110. I agree that assertions are probably an array (it's not just editorial, and there's another issue open on that) + for the very same reasons you mention I would suggest we remove saml2 assertions from the core (but still we can plan an extension in the registry, already mentioned as a possibility ).

**Comment by fimbault** [comment]
There's now a security consideration related to XML.
