### ISSUE TITLE
TLS at the "socket layer"

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#410]
The last paragraph of Sec. 12.2 is a bit off.

From an IETF perspective, we should be using "transport layer" (TCP, or OSI layer 4) instead of "socket layer".

More importantly, modern TLS uses session resumption heavily, meaning that the trust relationship does not end when the L4 connection ends. Granted that we often need to re-authenticate, but the explanation should be more precise.

**Comment by jricher** [comment]
If you can, please provide more precise text to help this section out. Thanks!

**Comment by adeinega** [comment]
@yaronf, I cannot agree more on that.

The specification may also suggest setting the Connection HTTP header to "close" when it isn't desirable to not reuse the same connection.

**Comment by fimbault** [comment]
It seems the initial intent is indeed to go beyond mutual authentication, although the related "discontinuity" risks are not called out.

For my understanding, by TLS continuity, do we mean a way to resume sessions ? Like session ID or session tickets or PSK ? Or something else ?

In my view (perhaps incorrect, because I'm just a basic user of such systems, not a TLS/mTLS designer) : a big part of the difference between TLS + PSK and mTLS seems related to key management. 
- with PSK a secret key is shared between client and server, so we get back to the discussion on out of band key distribution
- with PKI, we only need one private key per entity, and possibly the setup is simplified by a trusted certificate chain

**Comment by yaronf** [comment]
I would suggest to drop the "continuity" word, and instead, have a normative statement saying that both client and server (server only when using MTLS) MUST validate the other party's identity (RFC 6125-bis, possibly with our own twist) on each new L4 connection.

**Comment by fimbault** [comment]
Yes, we'll do that.
