### ISSUE TITLE
Logo by value

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#48]
§2.3.3 Providing Displayable RC Information

Editor's note: 

Would we want to support pushing a display logo by value? On the upside it allows for more dynamic detached clients and doesn't require the AS to fetch information. On the downside, this is harder for the AS to enforce a policy about and could lead to potential exploits caused by sending binary image files.

**Comment by aaronpk** [comment]
Technically the spec currently already allows this if `logo_uri` can be any URI, since you can embed an image with a `data:` URI.

**Comment by fimbault** [comment]
I've encountered the need to pass the logo by value. The rules to define which logo to display were complex, and so it seemed preferable to make sure the service would receive directly what it needed, instead of having to manage a large pool of reference URLs.

What we ended up doing is using data URI (inlined in base64), and limited to some specific MIME types (image/png).

**Comment by fimbault** [comment]
Should refer to https://datatracker.ietf.org/doc/html/rfc2397
