### ISSUE TITLE
User reference as an assertion

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#51]
§2.4.1 Identifying the User by Reference: Editor's note: 

We might be able to fold this function into an unstructured user assertion reference issued by the AS to the RC. We could put it in as an assertion type of "gnap_reference" or something like that. Downside: it's more verbose and potentially confusing to the client developer to have an assertion-like thing that's internal to the AS and not an assertion.

**Comment by fimbault** [comment]
Why an assertion? Is that reference supposed to be linked to a session (cf "represent the same end-user to the AS over subsequent requests") or can it be persistent?
I would see that more as an opaque identifier, rather than an assertion. 

Something like:
```
"user": {
   "sub_ids": [ {
     "subject_type": "as_ref",
     "as_ref": "XUT2MFM1XBIKJKSDU8QM"
   } ]
}
```

(there's a variety of names that we could choose, as_ref, local_uid, internal_uid, etc)
But that really asks what additional types we could define as part of secevents (section 7.1.2). 

Beyond the case mentioned here, it would be most useful as an opaque identifier when RO != end-user, to avoid leaking private info about the RO.

**Comment by jricher** [comment]
A subject identifier makes sense here, and I agree that it should be a new `subject_type` value to let us constrain it to the GNAP context.

**Comment by fimbault** [comment]
Fixed by SECEVENT opaque identifiers
