### ISSUE TITLE
Unique callback URIs

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#55]
§2.5.3 Receive a Callback After Interaction: Editor's note: 

Should we enforce the callback URI to be unique per request? That helps with some fixation attacks, but not with others, and it would be problematic for an AS that wants to lock down each client instance to a single callback instead of a family/pattern of callbacks.

**Comment by jricher** [comment]
Editors suggest closing as there are valid reasons for an AS to require an exact match of a single callback URI, such as establishing a client's identity without any pre-registration.

**Comment by dickhardt** [comment]
What are the attacks that are still possible with a unique callback URL?

AS already lock down from a family or URLs. Or the callback could be a fixed URL with a parameter that makes the URL unique.

**Comment by aaronpk** [comment]
The question in this issue is whether to *require* unique URLs, or whether the current text that allows stable URLs as well as unique URLs is okay.

Stable redirect URLs have a number of advantages, such as being able to be compared with exact string matching rather than needing to parse the URL and compare host/path/query/etc components. If the AS needs to be able to parse the URL, that opens up a whole world of [possible SSRF attacks](https://www.blackhat.com/docs/us-17/thursday/us-17-Tsai-A-New-Era-Of-SSRF-Exploiting-URL-Parser-In-Trending-Programming-Languages.pdf) that are avoided with simple string matching.
